"""empty message

Revision ID: 1ae3453ca74d
Revises: aba46c60af35
Create Date: 2016-05-30 21:29:43.288781

"""

# revision identifiers, used by Alembic.
revision = '1ae3453ca74d'
down_revision = 'aba46c60af35'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('client', sa.String(length=100), nullable=True),
                    sa.Column('rate', sa.String(length=100), nullable=True),
                    sa.Column('origin', sa.String(length=100), nullable=True),
                    sa.Column('destination', sa.String(length=100), nullable=True),
                    sa.Column('capacity', sa.String(length=100), nullable=True),
                    sa.Column('type', sa.String(length=100), nullable=True),
                    sa.Column('terms', sa.String(length=500), nullable=True),
                    sa.Column('manager', sa.String(length=100), nullable=True),
                    sa.Column('comments', sa.String(length=500), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('is_new', sa.Boolean(), nullable=True),
                    sa.Column('taken_by', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('rates_new')
    op.create_foreign_key(None, 'roles_users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.create_table('rates_new',
                    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
                    sa.Column('date', mysql.DATETIME(), nullable=True),
                    sa.Column('client', mysql.VARCHAR(length=100), nullable=True),
                    sa.Column('rate', mysql.VARCHAR(length=100), nullable=True),
                    sa.Column('origin', mysql.VARCHAR(length=100), nullable=True),
                    sa.Column('destination', mysql.VARCHAR(length=100), nullable=True),
                    sa.Column('capacity', mysql.VARCHAR(length=100), nullable=True),
                    sa.Column('type', mysql.VARCHAR(length=100), nullable=True),
                    sa.Column('terms', mysql.VARCHAR(length=500), nullable=True),
                    sa.Column('manager', mysql.VARCHAR(length=100), nullable=True),
                    sa.Column('comments', mysql.VARCHAR(length=500), nullable=True),
                    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('is_new', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.Column('taken_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='utf8',
                    mysql_engine='MyISAM'
                    )
    op.drop_table('rates')
    ### end Alembic commands ###
