"""empty message

Revision ID: aba46c60af35
Revises: None
Create Date: 2016-05-30 21:28:28.438418

"""

# revision identifiers, used by Alembic.
revision = 'aba46c60af35'
down_revision = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('operation', sa.String(length=200), nullable=True),
                    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rates_new',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('client', sa.String(length=100), nullable=True),
                    sa.Column('rate', sa.String(length=100), nullable=True),
                    sa.Column('origin', sa.String(length=100), nullable=True),
                    sa.Column('destination', sa.String(length=100), nullable=True),
                    sa.Column('capacity', sa.String(length=100), nullable=True),
                    sa.Column('type', sa.String(length=100), nullable=True),
                    sa.Column('terms', sa.String(length=500), nullable=True),
                    sa.Column('manager', sa.String(length=100), nullable=True),
                    sa.Column('comments', sa.String(length=500), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('is_new', sa.Boolean(), nullable=True),
                    sa.Column('taken_by', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('password', sa.String(length=255), nullable=True),
                    sa.Column('first_name', sa.String(length=255), nullable=True),
                    sa.Column('last_name', sa.String(length=255), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
                    sa.Column('last_login_at', sa.DateTime(), nullable=True),
                    sa.Column('current_login_at', sa.DateTime(), nullable=True),
                    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
                    sa.Column('current_login_ip', sa.String(length=45), nullable=True),
                    sa.Column('login_count', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('roles_users',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('rates_new')
    op.drop_table('operations')
    ### end Alembic commands ###
